/**
 * Speed test using same-origin test files (no CORS) for download/ping
 * and httpbun.com (CORS-enabled Cloudflare Workers service) for upload.
 *
 * speed.cloudflare.com/__down cannot be used from third-party origins —
 * it returns Access-Control-Allow-Origin: speed.cloudflare.com (invalid
 * value that browsers reject). See github.com/cloudflare/speedtest/issues/38
 */

// Same-origin test files generated by scripts/generate-test-files.mjs
// BASE_URL is '/' in dev and '/Showmyspeed/' in production (GitHub Pages)
const BASE = import.meta.env.BASE_URL
const LARGE_FILE = `${BASE}speedtest/10mb.bin`

// Fallback ping URLs — tried in order; index.html always exists since the app is loaded
const PING_CANDIDATES = [
  `${BASE}speedtest/ping.bin`,  // dedicated 1 KB ping file
  `${BASE}`,                     // index.html — guaranteed to exist
]

// Upload endpoints tried in order — first responding one is used for the full test.
// /upload is the self-hosted endpoint (available when running on showmyspeed.com).
// Falls back to third-party mirrors on GitHub Pages / local dev.
const UPLOAD_ENDPOINTS = [
  '/upload',                    // self-hosted nginx endpoint — same-origin, no CORS needed
  'https://httpbun.com/post',   // httpbin fork, Cloudflare Workers
  'https://httpbin.org/post',   // classic httpbin fallback
]

// ── Ping ─────────────────────────────────────────────────────────────────────

async function measureRtt(signal?: AbortSignal): Promise<number | null> {
  for (const url of PING_CANDIDATES) {
    try {
      const start = performance.now()
      // HEAD request — measures RTT without downloading a body
      const res = await fetch(`${url}?_=${Date.now()}`, { method: 'HEAD', signal })
      if (res.ok) return performance.now() - start
    } catch { /* try next candidate */ }
  }
  return null
}

export async function measurePing(
  samples = 8,
  onProgress?: (ping: number, jitter: number) => void,
  signal?: AbortSignal
): Promise<{ ping: number; jitter: number }> {
  // Warm up: first request includes TCP + TLS handshake — discard its timing
  try {
    await fetch(`${PING_CANDIDATES[0]}?warmup=${Date.now()}`, { method: 'HEAD', signal })
  } catch { /* ignore — warmup failure is fine, real samples follow */ }

  const rtts: number[] = []

  for (let i = 0; i < samples; i++) {
    if (signal?.aborted) break
    const rtt = await measureRtt(signal)
    if (rtt == null) continue
    rtts.push(rtt)

    const sorted = [...rtts].sort((a, b) => a - b)
    const median = sorted[Math.floor(sorted.length / 2)]
    const mean = rtts.reduce((s, v) => s + v, 0) / rtts.length
    const jitter =
      rtts.length > 1
        ? Math.sqrt(rtts.reduce((s, v) => s + (v - mean) ** 2, 0) / rtts.length)
        : 0
    onProgress?.(Math.round(median), Math.round(jitter))
  }

  if (rtts.length === 0) throw new Error('Ping failed — cannot reach test server')

  const sorted = [...rtts].sort((a, b) => a - b)
  const median = sorted[Math.floor(sorted.length / 2)]
  const mean = rtts.reduce((s, v) => s + v, 0) / rtts.length
  const jitter =
    rtts.length > 1
      ? Math.sqrt(rtts.reduce((s, v) => s + (v - mean) ** 2, 0) / rtts.length)
      : 0

  return { ping: Math.round(median), jitter: Math.round(jitter) }
}

// ── Download ──────────────────────────────────────────────────────────────────

const DOWNLOAD_DURATION_MS = 10_000  // fixed test window
const SAMPLE_INTERVAL_MS   = 200     // throughput sampling granularity
const WARMUP_DISCARD_MS    = 2_000   // discard first 2 s (TCP slow-start across 4 streams)
const DOWNLOAD_STREAMS     = 4       // parallel connections

/**
 * Streams LARGE_FILE repeatedly for DOWNLOAD_DURATION_MS across
 * DOWNLOAD_STREAMS parallel connections, sampling instantaneous throughput
 * every SAMPLE_INTERVAL_MS. Discards the first WARMUP_DISCARD_MS of samples
 * (TCP slow-start) and returns the 90th-percentile of the remainder.
 *
 * This matches the approach used by Cloudflare Speed Test / Netflix Fast.com:
 * a fixed-duration measurement that reaches steady-state throughput rather
 * than averaging over a short all-or-nothing buffer download.
 */
export async function measureDownload(
  onProgress: (mbps: number) => void,
  signal?: AbortSignal
): Promise<number> {
  let totalBytes = 0
  const testStart = performance.now()

  // Inner controller — stops workers after DOWNLOAD_DURATION_MS
  const inner = new AbortController()
  signal?.addEventListener('abort', () => inner.abort(), { once: true })
  const stopTimer = setTimeout(() => inner.abort(), DOWNLOAD_DURATION_MS)

  // Each worker streams LARGE_FILE in a loop until the inner signal fires
  async function streamWorker(idx: number) {
    while (!inner.signal.aborted) {
      let reader: ReadableStreamDefaultReader<Uint8Array> | null = null
      try {
        const res = await fetch(
          `${LARGE_FILE}?s=${idx}&_=${Date.now()}`,
          { signal: inner.signal, cache: 'no-store' },
        )
        if (!res.ok || !res.body) break
        reader = res.body.getReader()
        while (!inner.signal.aborted) {
          const { done, value } = await reader.read()
          if (done) break
          totalBytes += value.byteLength
        }
      } catch {
        break  // AbortError or network error — worker exits cleanly
      } finally {
        reader?.cancel().catch(() => {})
      }
    }
  }

  // Sampler: snapshots delta bytes every SAMPLE_INTERVAL_MS
  const timedSamples: Array<{ mbps: number; t: number }> = []
  let lastBytes = 0
  let lastTime  = testStart

  const ticker = setInterval(() => {
    const now   = performance.now()
    const dt    = now - lastTime
    const delta = totalBytes - lastBytes
    if (dt > 0) {
      timedSamples.push({ mbps: (delta * 8) / (dt / 1000) / 1_000_000, t: now - testStart })
      lastBytes = totalBytes
      lastTime  = now
      // Live progress: running median of post-warmup samples
      const valid = timedSamples.filter(s => s.t > WARMUP_DISCARD_MS).map(s => s.mbps)
      if (valid.length > 0) {
        const sorted = [...valid].sort((a, b) => a - b)
        onProgress(Math.round(sorted[Math.floor(sorted.length / 2)] * 10) / 10)
      }
    }
  }, SAMPLE_INTERVAL_MS)

  try {
    await Promise.allSettled(Array.from({ length: DOWNLOAD_STREAMS }, (_, i) => streamWorker(i)))
  } finally {
    clearInterval(ticker)
    clearTimeout(stopTimer)
  }

  const valid = timedSamples.filter(s => s.t > WARMUP_DISCARD_MS).map(s => s.mbps)

  if (valid.length === 0) {
    // Fallback: use total bytes / elapsed when not enough windowed samples
    const elapsed = (performance.now() - testStart) / 1000
    if (totalBytes > 0 && elapsed > 0) {
      return Math.round((totalBytes * 8) / elapsed / 1_000_000 * 10) / 10
    }
    throw new Error(
      'Download test failed — test files may not be deployed yet. ' +
      `Tried: ${LARGE_FILE}`,
    )
  }

  const sorted = [...valid].sort((a, b) => a - b)
  return Math.round(sorted[Math.floor(sorted.length * 0.9)] * 10) / 10
}

// ── Upload ────────────────────────────────────────────────────────────────────

const UPLOAD_DURATION_MS = 10_000   // fixed test window
const UPLOAD_WARMUP_MS   = 2_000    // discard first 2 s (mirrors download warmup)
const UPLOAD_STREAMS     = 3        // parallel connections
const UPLOAD_CHUNK_BYTES = 8_000_000 // 8 MB per chunk — large enough for continuous flow

/** Send 50 KB probe to each endpoint in order; return first URL that responds */
async function findUploadEndpoint(signal?: AbortSignal): Promise<string | null> {
  for (const url of UPLOAD_ENDPOINTS) {
    const ok = await new Promise<boolean>((resolve) => {
      const xhr = new XMLHttpRequest()
      const onAbort = () => { xhr.abort(); resolve(false) }
      signal?.addEventListener('abort', onAbort, { once: true })
      xhr.onload    = () => { signal?.removeEventListener('abort', onAbort); resolve(xhr.status >= 200 && xhr.status < 300) }
      xhr.onerror   = () => { signal?.removeEventListener('abort', onAbort); resolve(false) }
      xhr.ontimeout = () => { signal?.removeEventListener('abort', onAbort); resolve(false) }
      xhr.timeout   = 8_000
      xhr.open('POST', url)
      xhr.send(new Blob([new Uint8Array(50_000)], { type: 'application/octet-stream' }))
    })
    if (ok) { console.info(`Upload endpoint: ${url}`); return url }
  }
  return null
}

/**
 * Mirrors measureDownload exactly: N parallel workers each POST UPLOAD_CHUNK_BYTES
 * in a loop, reporting bytes sent via xhr.upload.onprogress into a shared counter.
 * An interval sampler snapshots throughput every SAMPLE_INTERVAL_MS; the first
 * UPLOAD_WARMUP_MS of samples are discarded, and the 90th percentile is returned.
 */
export async function measureUpload(
  onProgress: (mbps: number) => void,
  signal?: AbortSignal,
): Promise<number> {
  const uploadUrl = (await findUploadEndpoint(signal)) as string
  if (!uploadUrl) throw new Error('No upload endpoint available')

  // Pre-allocate once; Blob constructor copies the buffer anyway
  const uploadBuffer = new Uint8Array(UPLOAD_CHUNK_BYTES)

  let totalBytes = 0
  const testStart = performance.now()

  const inner = new AbortController()
  signal?.addEventListener('abort', () => inner.abort(), { once: true })
  const stopTimer = setTimeout(() => inner.abort(), UPLOAD_DURATION_MS)

  async function uploadWorker() {
    while (!inner.signal.aborted) {
      let lastLoaded = 0
      await new Promise<void>((resolve) => {
        const xhr = new XMLHttpRequest()
        const onAbort = () => { xhr.abort(); resolve() }
        inner.signal.addEventListener('abort', onAbort, { once: true })
        xhr.upload.onprogress = (e) => {
          totalBytes += e.loaded - lastLoaded
          lastLoaded = e.loaded
        }
        xhr.onload    = () => { inner.signal.removeEventListener('abort', onAbort); resolve() }
        xhr.onerror   = () => { inner.signal.removeEventListener('abort', onAbort); resolve() }
        xhr.ontimeout = () => { inner.signal.removeEventListener('abort', onAbort); resolve() }
        xhr.timeout   = 60_000
        xhr.open('POST', uploadUrl)
        xhr.send(new Blob([uploadBuffer], { type: 'application/octet-stream' }))
      })
    }
  }

  const timedSamples: Array<{ mbps: number; t: number }> = []
  let lastBytes = 0
  let lastTime  = testStart

  const ticker = setInterval(() => {
    const now   = performance.now()
    const dt    = now - lastTime
    const delta = totalBytes - lastBytes
    if (dt > 0) {
      timedSamples.push({ mbps: (delta * 8) / (dt / 1000) / 1_000_000, t: now - testStart })
      lastBytes = totalBytes
      lastTime  = now
      const valid = timedSamples.filter(s => s.t > UPLOAD_WARMUP_MS).map(s => s.mbps)
      if (valid.length > 0) {
        const sorted = [...valid].sort((a, b) => a - b)
        onProgress(Math.round(sorted[Math.floor(sorted.length / 2)] * 10) / 10)
      }
    }
  }, SAMPLE_INTERVAL_MS)

  try {
    await Promise.allSettled(Array.from({ length: UPLOAD_STREAMS }, () => uploadWorker()))
  } finally {
    clearInterval(ticker)
    clearTimeout(stopTimer)
  }

  const valid = timedSamples.filter(s => s.t > UPLOAD_WARMUP_MS).map(s => s.mbps)

  if (valid.length === 0) {
    const elapsed = (performance.now() - testStart) / 1000
    if (totalBytes > 0 && elapsed > 0) {
      return Math.round((totalBytes * 8) / elapsed / 1_000_000 * 10) / 10
    }
    throw new Error('Upload test failed')
  }

  const sorted = [...valid].sort((a, b) => a - b)
  return Math.round(sorted[Math.floor(sorted.length * 0.9)] * 10) / 10
}

// ── Speed Score ───────────────────────────────────────────────────────────────

/** Returns a 0–100 composite score and a human label for the connection quality. */
export function getSpeedScore(result: { download: number; upload: number; ping: number; jitter: number }): {
  score: number
  label: string
  color: string
} {
  // Weights: download 40 | upload 20 | ping 25 | jitter 15  (total = 100)
  // Caps: 200 Mbps download, 50 Mbps upload, 200 ms ping, 50 ms jitter
  const downloadScore = Math.min(result.download / 200, 1) * 40
  const uploadScore   = Math.min(result.upload   /  50, 1) * 20
  const pingScore     = (1 - Math.min(result.ping   / 200, 1)) * 25
  const jitterScore   = (1 - Math.min(result.jitter /  50, 1)) * 15
  const score = Math.round(downloadScore + uploadScore + pingScore + jitterScore)

  let label: string
  let color: string
  if      (score >= 85) { label = 'Excellent'; color = '#34d399' }
  else if (score >= 70) { label = 'Great';     color = '#22d3ee' }
  else if (score >= 50) { label = 'Good';      color = '#fbbf24' }
  else if (score >= 30) { label = 'Fair';      color = '#f97316' }
  else                  { label = 'Poor';      color = '#f87171' }

  return { score, label, color }
}

/**
 * Estimates what percentile a given speed falls in using a log-normal
 * approximation fitted to Ookla Q4 2024 global fixed broadband averages.
 * Returns a value from 1 to 99.
 */
export function estimatePercentile(speed: number, type: 'download' | 'upload'): number {
  const median = type === 'download' ? 90 : 30   // global medians in Mbps
  const sigma  = 1.1                              // log-normal shape parameter

  const z = (Math.log(Math.max(speed, 0.1)) - Math.log(median)) / sigma

  // Abramowitz & Stegun normal CDF approximation (error < 7.5e-8)
  const absZ = Math.abs(z)
  const t    = 1 / (1 + 0.2316419 * absZ)
  const d    = 0.3989422804 * Math.exp(-0.5 * absZ * absZ)
  const poly = t * (0.319381530 + t * (-0.356563782 + t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))))
  const cdf  = z >= 0 ? 1 - d * poly : d * poly

  return Math.round(Math.max(1, Math.min(99, cdf * 100)))
}

// ── IP Info ───────────────────────────────────────────────────────────────────

export async function fetchIpInfo() {
  try {
    const res = await fetch(
      `https://ip-api.com/json/?fields=status,city,country,isp,org,query&_=${Date.now()}`
    )
    const data = await res.json()
    if (data.status === 'success') {
      return {
        ip: data.query as string,
        isp: (data.isp || data.org || 'Unknown') as string,
        city: data.city as string,
        country: data.country as string,
        org: data.org as string,
      }
    }
  } catch {
    // silently ignore
  }
  return null
}
