/**
 * Speed test using same-origin test files (no CORS) for download/ping
 * and httpbun.com (CORS-enabled Cloudflare Workers service) for upload.
 *
 * speed.cloudflare.com/__down cannot be used from third-party origins —
 * it returns Access-Control-Allow-Origin: speed.cloudflare.com (invalid
 * value that browsers reject). See github.com/cloudflare/speedtest/issues/38
 */

// Same-origin test files generated by scripts/generate-test-files.mjs
// BASE_URL is '/' in dev and '/Showmyspeed/' in production (GitHub Pages)
const BASE = import.meta.env.BASE_URL
const SMALL_FILE = `${BASE}speedtest/1mb.bin`
const LARGE_FILE = `${BASE}speedtest/10mb.bin`

// Fallback ping URLs — tried in order; index.html always exists since the app is loaded
const PING_CANDIDATES = [
  `${BASE}speedtest/ping.bin`,  // dedicated 1 KB ping file
  `${BASE}`,                     // index.html — guaranteed to exist
]

// httpbun.com: maintained httpbin fork on Cloudflare Workers with Access-Control-Allow-Origin: *
const UPLOAD_URL = 'https://httpbun.com/post'

// ── Ping ─────────────────────────────────────────────────────────────────────

async function measureRtt(signal?: AbortSignal): Promise<number | null> {
  for (const url of PING_CANDIDATES) {
    try {
      const start = performance.now()
      // HEAD request — measures RTT without downloading a body
      const res = await fetch(`${url}?_=${Date.now()}`, { method: 'HEAD', signal })
      if (res.ok) return performance.now() - start
    } catch { /* try next candidate */ }
  }
  return null
}

export async function measurePing(
  samples = 6,
  onProgress?: (ping: number, jitter: number) => void,
  signal?: AbortSignal
): Promise<{ ping: number; jitter: number }> {
  const rtts: number[] = []

  for (let i = 0; i < samples; i++) {
    if (signal?.aborted) break
    const rtt = await measureRtt(signal)
    if (rtt == null) continue
    rtts.push(rtt)

    const sorted = [...rtts].sort((a, b) => a - b)
    const median = sorted[Math.floor(sorted.length / 2)]
    const mean = rtts.reduce((s, v) => s + v, 0) / rtts.length
    const jitter =
      rtts.length > 1
        ? Math.sqrt(rtts.reduce((s, v) => s + (v - mean) ** 2, 0) / rtts.length)
        : 0
    onProgress?.(Math.round(median), Math.round(jitter))
  }

  if (rtts.length === 0) throw new Error('Ping failed — cannot reach test server')

  const sorted = [...rtts].sort((a, b) => a - b)
  const median = sorted[Math.floor(sorted.length / 2)]
  const mean = rtts.reduce((s, v) => s + v, 0) / rtts.length
  const jitter =
    rtts.length > 1
      ? Math.sqrt(rtts.reduce((s, v) => s + (v - mean) ** 2, 0) / rtts.length)
      : 0

  return { ping: Math.round(median), jitter: Math.round(jitter) }
}

// ── Download ──────────────────────────────────────────────────────────────────

async function downloadChunk(
  url: string,
  signal?: AbortSignal
): Promise<number | null> {
  try {
    const start = performance.now()
    const res = await fetch(`${url}?_=${Date.now()}`, { signal })
    if (!res.ok) return null
    const buffer = await res.arrayBuffer()
    const elapsed = (performance.now() - start) / 1000
    if (elapsed === 0) return null
    return (buffer.byteLength * 8) / elapsed / 1_000_000
  } catch {
    return null
  }
}

export async function measureDownload(
  onProgress: (mbps: number) => void,
  signal?: AbortSignal
): Promise<number> {
  // Stages: start with 1 MB file (warm-up) then switch to 10 MB file
  const stages: Array<{ url: string; runs: number; warmup?: boolean }> = [
    { url: SMALL_FILE, runs: 2, warmup: true },  // warm up connection
    { url: LARGE_FILE, runs: 2 },                 // accurate measurement
    { url: LARGE_FILE, runs: 2 },
  ]

  const samples: number[] = []

  for (const stage of stages) {
    if (signal?.aborted) break
    for (let i = 0; i < stage.runs; i++) {
      if (signal?.aborted) break
      const mbps = await downloadChunk(stage.url, signal)
      if (mbps == null) continue
      if (!stage.warmup) {
        samples.push(mbps)
        const avg = samples.reduce((s, v) => s + v, 0) / samples.length
        onProgress(Math.round(avg * 10) / 10)
      }
    }
  }

  if (samples.length === 0) throw new Error(
    'Download test failed — test files may not be deployed yet. ' +
    `Tried: ${SMALL_FILE} and ${LARGE_FILE}`
  )
  const sorted = [...samples].sort((a, b) => a - b)
  // 90th-percentile of samples
  return Math.round(sorted[Math.floor(sorted.length * 0.9)] * 10) / 10
}

// ── Upload ────────────────────────────────────────────────────────────────────

function uploadChunk(
  bytes: number,
  onProgress: (mbps: number) => void,
  signal?: AbortSignal
): Promise<number | null> {
  return new Promise((resolve) => {
    // text/plain keeps the CORS request "simple" (no preflight)
    const blob = new Blob([new Uint8Array(bytes)], { type: 'text/plain' })
    const xhr = new XMLHttpRequest()
    const start = performance.now()
    let lastLoaded = 0
    let lastTime = start

    const onAbort = () => {
      xhr.abort()
      resolve(null)
    }
    signal?.addEventListener('abort', onAbort, { once: true })

    xhr.upload.onprogress = (e) => {
      const now = performance.now()
      const dt = (now - lastTime) / 1000
      const dl = e.loaded - lastLoaded
      if (dt > 0.1 && dl > 0) {
        onProgress(Math.round(((dl * 8) / dt / 1_000_000) * 10) / 10)
        lastLoaded = e.loaded
        lastTime = now
      }
    }

    xhr.onload = () => {
      signal?.removeEventListener('abort', onAbort)
      const elapsed = (performance.now() - start) / 1000
      resolve(
        elapsed > 0
          ? Math.round(((bytes * 8) / elapsed / 1_000_000) * 10) / 10
          : null
      )
    }

    xhr.onerror = () => {
      signal?.removeEventListener('abort', onAbort)
      resolve(null)
    }

    xhr.ontimeout = () => {
      signal?.removeEventListener('abort', onAbort)
      resolve(null)
    }

    xhr.timeout = 30_000
    xhr.open('POST', UPLOAD_URL)
    xhr.send(blob)
  })
}

export async function measureUpload(
  onProgress: (mbps: number) => void,
  signal?: AbortSignal
): Promise<number> {
  const stages: Array<{ bytes: number; runs: number }> = [
    { bytes: 500_000, runs: 1 },    // warm-up
    { bytes: 2_000_000, runs: 3 },
    { bytes: 5_000_000, runs: 2 },
  ]

  const samples: number[] = []

  for (const stage of stages) {
    if (signal?.aborted) break
    for (let i = 0; i < stage.runs; i++) {
      if (signal?.aborted) break
      const mbps = await uploadChunk(stage.bytes, onProgress, signal)
      if (mbps == null) continue
      if (stage.bytes > 500_000) {
        samples.push(mbps)
        const avg = samples.reduce((s, v) => s + v, 0) / samples.length
        onProgress(Math.round(avg * 10) / 10)
      }
    }
  }

  if (samples.length === 0) throw new Error('Upload test failed')
  const sorted = [...samples].sort((a, b) => a - b)
  return Math.round(sorted[Math.floor(sorted.length * 0.9)] * 10) / 10
}

// ── IP Info ───────────────────────────────────────────────────────────────────

export async function fetchIpInfo() {
  try {
    const res = await fetch(
      `https://ip-api.com/json/?fields=status,city,country,isp,org,query&_=${Date.now()}`
    )
    const data = await res.json()
    if (data.status === 'success') {
      return {
        ip: data.query as string,
        isp: (data.isp || data.org || 'Unknown') as string,
        city: data.city as string,
        country: data.country as string,
        org: data.org as string,
      }
    }
  } catch {
    // silently ignore
  }
  return null
}
