/**
 * Speed test using same-origin test files (no CORS) for download/ping
 * and httpbun.com (CORS-enabled Cloudflare Workers service) for upload.
 *
 * speed.cloudflare.com/__down cannot be used from third-party origins —
 * it returns Access-Control-Allow-Origin: speed.cloudflare.com (invalid
 * value that browsers reject). See github.com/cloudflare/speedtest/issues/38
 */

// Same-origin test files generated by scripts/generate-test-files.mjs
// BASE_URL is '/' in dev and '/Showmyspeed/' in production (GitHub Pages)
const BASE = import.meta.env.BASE_URL
const LARGE_FILE = `${BASE}speedtest/10mb.bin`

// Fallback ping URLs — tried in order; index.html always exists since the app is loaded
const PING_CANDIDATES = [
  `${BASE}speedtest/ping.bin`,  // dedicated 1 KB ping file
  `${BASE}`,                     // index.html — guaranteed to exist
]

// Upload endpoints tried in order — first responding one is used for the full test.
// /upload is the self-hosted endpoint (available when running on showmyspeed.com).
// Falls back to third-party mirrors on GitHub Pages / local dev.
const UPLOAD_ENDPOINTS = [
  '/upload',                    // self-hosted nginx endpoint — same-origin, no CORS needed
  'https://httpbun.com/post',   // httpbin fork, Cloudflare Workers
  'https://httpbin.org/post',   // classic httpbin fallback
]

// ── Ping ─────────────────────────────────────────────────────────────────────

async function measureRtt(signal?: AbortSignal): Promise<number | null> {
  for (const url of PING_CANDIDATES) {
    try {
      const start = performance.now()
      // HEAD request — measures RTT without downloading a body
      const res = await fetch(`${url}?_=${Date.now()}`, { method: 'HEAD', signal })
      if (res.ok) return performance.now() - start
    } catch { /* try next candidate */ }
  }
  return null
}

export async function measurePing(
  samples = 6,
  onProgress?: (ping: number, jitter: number) => void,
  signal?: AbortSignal
): Promise<{ ping: number; jitter: number }> {
  const rtts: number[] = []

  for (let i = 0; i < samples; i++) {
    if (signal?.aborted) break
    const rtt = await measureRtt(signal)
    if (rtt == null) continue
    rtts.push(rtt)

    const sorted = [...rtts].sort((a, b) => a - b)
    const median = sorted[Math.floor(sorted.length / 2)]
    const mean = rtts.reduce((s, v) => s + v, 0) / rtts.length
    const jitter =
      rtts.length > 1
        ? Math.sqrt(rtts.reduce((s, v) => s + (v - mean) ** 2, 0) / rtts.length)
        : 0
    onProgress?.(Math.round(median), Math.round(jitter))
  }

  if (rtts.length === 0) throw new Error('Ping failed — cannot reach test server')

  const sorted = [...rtts].sort((a, b) => a - b)
  const median = sorted[Math.floor(sorted.length / 2)]
  const mean = rtts.reduce((s, v) => s + v, 0) / rtts.length
  const jitter =
    rtts.length > 1
      ? Math.sqrt(rtts.reduce((s, v) => s + (v - mean) ** 2, 0) / rtts.length)
      : 0

  return { ping: Math.round(median), jitter: Math.round(jitter) }
}

// ── Download ──────────────────────────────────────────────────────────────────

const DOWNLOAD_DURATION_MS = 8_000  // fixed test window
const SAMPLE_INTERVAL_MS   = 200    // throughput sampling granularity
const WARMUP_DISCARD_MS    = 1_000  // discard first 1 s (TCP slow-start)
const DOWNLOAD_STREAMS     = 2      // parallel connections

/**
 * Streams LARGE_FILE repeatedly for DOWNLOAD_DURATION_MS across
 * DOWNLOAD_STREAMS parallel connections, sampling instantaneous throughput
 * every SAMPLE_INTERVAL_MS. Discards the first WARMUP_DISCARD_MS of samples
 * (TCP slow-start) and returns the 90th-percentile of the remainder.
 *
 * This matches the approach used by Cloudflare Speed Test / Netflix Fast.com:
 * a fixed-duration measurement that reaches steady-state throughput rather
 * than averaging over a short all-or-nothing buffer download.
 */
export async function measureDownload(
  onProgress: (mbps: number) => void,
  signal?: AbortSignal
): Promise<number> {
  let totalBytes = 0
  const testStart = performance.now()

  // Inner controller — stops workers after DOWNLOAD_DURATION_MS
  const inner = new AbortController()
  signal?.addEventListener('abort', () => inner.abort(), { once: true })
  const stopTimer = setTimeout(() => inner.abort(), DOWNLOAD_DURATION_MS)

  // Each worker streams LARGE_FILE in a loop until the inner signal fires
  async function streamWorker(idx: number) {
    while (!inner.signal.aborted) {
      let reader: ReadableStreamDefaultReader<Uint8Array> | null = null
      try {
        const res = await fetch(
          `${LARGE_FILE}?s=${idx}&_=${Date.now()}`,
          { signal: inner.signal, cache: 'no-store' },
        )
        if (!res.ok || !res.body) break
        reader = res.body.getReader()
        while (!inner.signal.aborted) {
          const { done, value } = await reader.read()
          if (done) break
          totalBytes += value.byteLength
        }
      } catch {
        break  // AbortError or network error — worker exits cleanly
      } finally {
        reader?.cancel().catch(() => {})
      }
    }
  }

  // Sampler: snapshots delta bytes every SAMPLE_INTERVAL_MS
  const timedSamples: Array<{ mbps: number; t: number }> = []
  let lastBytes = 0
  let lastTime  = testStart

  const ticker = setInterval(() => {
    const now   = performance.now()
    const dt    = now - lastTime
    const delta = totalBytes - lastBytes
    if (dt > 0) {
      timedSamples.push({ mbps: (delta * 8) / (dt / 1000) / 1_000_000, t: now - testStart })
      lastBytes = totalBytes
      lastTime  = now
      // Live progress: running median of post-warmup samples
      const valid = timedSamples.filter(s => s.t > WARMUP_DISCARD_MS).map(s => s.mbps)
      if (valid.length > 0) {
        const sorted = [...valid].sort((a, b) => a - b)
        onProgress(Math.round(sorted[Math.floor(sorted.length / 2)] * 10) / 10)
      }
    }
  }, SAMPLE_INTERVAL_MS)

  try {
    await Promise.allSettled(Array.from({ length: DOWNLOAD_STREAMS }, (_, i) => streamWorker(i)))
  } finally {
    clearInterval(ticker)
    clearTimeout(stopTimer)
  }

  const valid = timedSamples.filter(s => s.t > WARMUP_DISCARD_MS).map(s => s.mbps)

  if (valid.length === 0) {
    // Fallback: use total bytes / elapsed when not enough windowed samples
    const elapsed = (performance.now() - testStart) / 1000
    if (totalBytes > 0 && elapsed > 0) {
      return Math.round((totalBytes * 8) / elapsed / 1_000_000 * 10) / 10
    }
    throw new Error(
      'Download test failed — test files may not be deployed yet. ' +
      `Tried: ${LARGE_FILE}`,
    )
  }

  const sorted = [...valid].sort((a, b) => a - b)
  return Math.round(sorted[Math.floor(sorted.length * 0.9)] * 10) / 10
}

// ── Upload ────────────────────────────────────────────────────────────────────

/**
 * POST `bytes` to `url`. Returns the end-to-end elapsed seconds, or null on
 * failure. Used for both the 50 KB endpoint probe and self-hosted warm-up.
 */
function uploadChunkTimed(
  url: string,
  bytes: number,
  signal?: AbortSignal,
  timeoutMs = 120_000,
): Promise<number | null> {
  return new Promise((resolve) => {
    const blob    = new Blob([new Uint8Array(bytes)], { type: 'text/plain' })
    const xhr     = new XMLHttpRequest()
    const start   = performance.now()
    const onAbort = () => { xhr.abort(); resolve(null) }
    signal?.addEventListener('abort', onAbort, { once: true })
    xhr.onload    = () => {
      signal?.removeEventListener('abort', onAbort)
      if (xhr.status < 200 || xhr.status >= 300) { resolve(null); return }
      resolve((performance.now() - start) / 1000)
    }
    xhr.onerror   = () => { signal?.removeEventListener('abort', onAbort); resolve(null) }
    xhr.ontimeout = () => { signal?.removeEventListener('abort', onAbort); resolve(null) }
    xhr.timeout   = timeoutMs
    xhr.open('POST', url)
    xhr.send(blob)
  })
}

/**
 * POST `bytes` to `url`, reporting instantaneous Mbps via `onProgress` every
 * 100 ms. Returns the end-to-end Mbps, or null on failure.
 * Used for the fallback (third-party) upload path.
 */
function uploadChunk(
  url: string,
  bytes: number,
  onProgress: (mbps: number) => void,
  signal?: AbortSignal,
): Promise<number | null> {
  return new Promise((resolve) => {
    const blob    = new Blob([new Uint8Array(bytes)], { type: 'text/plain' })
    const xhr     = new XMLHttpRequest()
    const start   = performance.now()
    let lastLoaded = 0
    let lastTime   = start
    const onAbort  = () => { xhr.abort(); resolve(null) }
    signal?.addEventListener('abort', onAbort, { once: true })
    xhr.upload.onprogress = (e) => {
      const now = performance.now()
      const dt  = (now - lastTime) / 1000
      const dl  = e.loaded - lastLoaded
      if (dt > 0.1 && dl > 0) {
        onProgress(Math.round(((dl * 8) / dt / 1_000_000) * 10) / 10)
        lastLoaded = e.loaded
        lastTime   = now
      }
    }
    xhr.onload    = () => {
      signal?.removeEventListener('abort', onAbort)
      if (xhr.status < 200 || xhr.status >= 300) { resolve(null); return }
      const elapsed = (performance.now() - start) / 1000
      resolve(elapsed > 0 ? Math.round(((bytes * 8) / elapsed / 1_000_000) * 10) / 10 : null)
    }
    xhr.onerror   = () => { signal?.removeEventListener('abort', onAbort); resolve(null) }
    xhr.ontimeout = () => { signal?.removeEventListener('abort', onAbort); resolve(null) }
    xhr.timeout   = 15_000
    xhr.open('POST', url)
    xhr.send(blob)
  })
}

/** Send 50 KB probe to each endpoint in order; return first URL that responds */
async function findUploadEndpoint(signal?: AbortSignal): Promise<string | null> {
  for (const url of UPLOAD_ENDPOINTS) {
    const elapsed = await uploadChunkTimed(url, 50_000, signal, 8_000)
    if (elapsed !== null) {
      console.info(`Upload endpoint: ${url}`)
      return url
    }
  }
  return null
}

export async function measureUpload(
  onProgress: (mbps: number) => void,
  signal?: AbortSignal,
): Promise<number> {
  const uploadUrl = await findUploadEndpoint(signal)
  if (!uploadUrl) throw new Error('No upload endpoint available')

  const isOwnServer = uploadUrl === '/upload'

  if (isOwnServer) {
    // ── Self-hosted path: adaptive chunks over a 10-second budget ────────────
    //
    // Strategy: warm up with 2 MB to estimate speed, then send chunks that
    // each target ~2 seconds of transfer time (capped 1–10 MB). Adaptive
    // sizing keeps the measurement window sensible across 1–1000+ Mbps.
    const BUDGET_MS = 10_000

    const warmupElapsed = await uploadChunkTimed(uploadUrl, 2_000_000, signal)
    if (warmupElapsed == null) throw new Error('Upload warm-up failed')

    const estimatedMbps = (2_000_000 * 8) / warmupElapsed / 1_000_000
    // Target 2-second chunks; clamp to [1 MB, 10 MB]
    const targetBytes = (estimatedMbps * 2 * 1_000_000) / 8
    let chunkBytes = Math.min(10_000_000, Math.max(1_000_000, Math.round(targetBytes)))

    const samples: number[] = []
    const budgetStart = performance.now()

    while (performance.now() - budgetStart < BUDGET_MS && !signal?.aborted) {
      const elapsed = await uploadChunkTimed(uploadUrl, chunkBytes, signal)
      if (elapsed == null) break

      const mbps = Math.round((chunkBytes * 8) / elapsed / 1_000_000 * 10) / 10
      samples.push(mbps)

      const sorted = [...samples].sort((a, b) => a - b)
      onProgress(Math.round(sorted[Math.floor(sorted.length / 2)] * 10) / 10)

      // Re-estimate chunk size based on the most recent measurement
      chunkBytes = Math.min(10_000_000, Math.max(1_000_000, Math.round((mbps * 2 * 1_000_000) / 8)))
    }

    if (samples.length === 0) throw new Error('Upload test failed')
    const sorted = [...samples].sort((a, b) => a - b)
    return Math.round(sorted[Math.floor(sorted.length * 0.9)] * 10) / 10

  } else {
    // ── Fallback path: 1 MB × 5 chunks — stays within third-party limits ─────
    const stages: Array<{ bytes: number; runs: number; warmup?: boolean }> = [
      { bytes: 500_000,   runs: 1, warmup: true },
      { bytes: 1_000_000, runs: 5 },
    ]
    const samples: number[] = []

    for (const stage of stages) {
      if (signal?.aborted) break
      for (let i = 0; i < stage.runs; i++) {
        if (signal?.aborted) break
        const mbps = await uploadChunk(uploadUrl, stage.bytes, onProgress, signal)
        if (mbps == null) continue
        if (!stage.warmup) {
          samples.push(mbps)
          onProgress(Math.round((samples.reduce((s, v) => s + v, 0) / samples.length) * 10) / 10)
        }
      }
    }

    if (samples.length === 0) throw new Error('Upload test failed')
    const sorted = [...samples].sort((a, b) => a - b)
    return Math.round(sorted[Math.floor(sorted.length * 0.9)] * 10) / 10
  }
}

// ── Speed Score ───────────────────────────────────────────────────────────────

/** Returns a 0–100 composite score and a human label for the connection quality. */
export function getSpeedScore(result: { download: number; upload: number; ping: number; jitter: number }): {
  score: number
  label: string
  color: string
} {
  // Weights: download 40 | upload 20 | ping 25 | jitter 15  (total = 100)
  // Caps: 200 Mbps download, 50 Mbps upload, 200 ms ping, 50 ms jitter
  const downloadScore = Math.min(result.download / 200, 1) * 40
  const uploadScore   = Math.min(result.upload   /  50, 1) * 20
  const pingScore     = (1 - Math.min(result.ping   / 200, 1)) * 25
  const jitterScore   = (1 - Math.min(result.jitter /  50, 1)) * 15
  const score = Math.round(downloadScore + uploadScore + pingScore + jitterScore)

  let label: string
  let color: string
  if      (score >= 85) { label = 'Excellent'; color = '#34d399' }
  else if (score >= 70) { label = 'Great';     color = '#22d3ee' }
  else if (score >= 50) { label = 'Good';      color = '#fbbf24' }
  else if (score >= 30) { label = 'Fair';      color = '#f97316' }
  else                  { label = 'Poor';      color = '#f87171' }

  return { score, label, color }
}

/**
 * Estimates what percentile a given speed falls in using a log-normal
 * approximation fitted to Ookla Q4 2024 global fixed broadband averages.
 * Returns a value from 1 to 99.
 */
export function estimatePercentile(speed: number, type: 'download' | 'upload'): number {
  const median = type === 'download' ? 90 : 30   // global medians in Mbps
  const sigma  = 1.1                              // log-normal shape parameter

  const z = (Math.log(Math.max(speed, 0.1)) - Math.log(median)) / sigma

  // Abramowitz & Stegun normal CDF approximation (error < 7.5e-8)
  const absZ = Math.abs(z)
  const t    = 1 / (1 + 0.2316419 * absZ)
  const d    = 0.3989422804 * Math.exp(-0.5 * absZ * absZ)
  const poly = t * (0.319381530 + t * (-0.356563782 + t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))))
  const cdf  = z >= 0 ? 1 - d * poly : d * poly

  return Math.round(Math.max(1, Math.min(99, cdf * 100)))
}

// ── IP Info ───────────────────────────────────────────────────────────────────

export async function fetchIpInfo() {
  try {
    const res = await fetch(
      `https://ip-api.com/json/?fields=status,city,country,isp,org,query&_=${Date.now()}`
    )
    const data = await res.json()
    if (data.status === 'success') {
      return {
        ip: data.query as string,
        isp: (data.isp || data.org || 'Unknown') as string,
        city: data.city as string,
        country: data.country as string,
        org: data.org as string,
      }
    }
  } catch {
    // silently ignore
  }
  return null
}
